// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shikimori.Data;

namespace Shikimori.Data.Migrations
{
    [DbContext(typeof(ShikimoriDbContext))]
    [Migration("20201227200112_AddSettings")]
    partial class AddSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GenreVideo", b =>
                {
                    b.Property<string>("GenresKey")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VideosUrl")
                        .HasColumnType("character varying(1000)");

                    b.HasKey("GenresKey", "VideosUrl");

                    b.HasIndex("VideosUrl");

                    b.ToTable("GenreVideo");
                });

            modelBuilder.Entity("Shikimori.Data.Models.Genre", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Key");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Shikimori.Data.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Shikimori.Data.Models.Video", b =>
                {
                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("TitleEng")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TitleRus")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Url");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("GenreVideo", b =>
                {
                    b.HasOne("Shikimori.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shikimori.Data.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("VideosUrl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
